# logging app
logging:
  level:
    org:
      springframework:
        jdbc:
          core:
            JdbcTemplate: DEBUG
            StatementCreatorUtils: TRACE
          datasource: TRACE
      hibernate:
        SQL:
          TRACE
        type:
          descriptor:
            sql:
              BasicBinder:
                TRACE

# org.springframework.jdbc.datasource
## datasource
spring:
  jpa:
    hibernate: {ddl-auto: none}
    properties:
      hibernate: {show_sql: true, format_sql: true, use_sql_comments: true, dialect: org.hibernate.spatial.dialect.mysql.MySQL8SpatialDialect}
  datasource: {url: 'jdbc:mysql://localhost:3306?useSSL=false&useTimezone=true&serverTimezone=UTC&allowPublicKeyRetrieval=true',
    username: root, password: root, initialization-mode: never, continue-on-error: false}
