
CREATE SCHEMA IF NOT EXISTS `principal`  ;

CREATE SCHEMA IF NOT EXISTS `sistema`  ;

CREATE SCHEMA IF NOT EXISTS `pessoa`  ;

CREATE SCHEMA IF NOT EXISTS `comum`  ;

CREATE SCHEMA IF NOT EXISTS `produto`  ;

CREATE SCHEMA IF NOT EXISTS `oauth2`  ;

CREATE SCHEMA IF NOT EXISTS `evento`  ;

CREATE SCHEMA IF NOT EXISTS `veiculo`  ;

CREATE SCHEMA IF NOT EXISTS `funcional`  ;

